### ISSUE TITLE
refactor launch_screen and user login

### ISSUE THREAD

**Issue by ozline** [west2-online/fzuhelper-server#14]
Currently our launch screen is an independent go program (https://github.com/west2-online/fzuhelper-launch-screen). We hope to integrate it into the current unified architecture. We need 1 volunteer to help complete it.

## Skills you may need

- Basic golang skills and entry-level distributed knowledge
- Familiar with our unified distributed architecture, or willing to learn this architecture
- Have some time - or be willing to be pushed

**Comment by jiuxia211** [comment]
assign @FantasyRL
