### ISSUE TITLE
Documentation Complete 

### ISSUE THREAD

**Issue by jiuxia211** [west2-online/fzuhelper-server#15]
Current, this project has some changes compared to [tiktok](https://github.com/ozline/tiktok), and it is necessary to write a beginner-oriented document (README) for new contributors to quickly get started. Its main content should include:
1. Basic introduction of the project
2. The basic structure tree of the project and the functions of each part
3. How to start/deploy this project?
Of course, you are welcome to provide more and more complete content

**Comment by YuGgge** [comment]
I would like to work on this issue.
