### ISSUE TITLE
Using Kafka instead of RabbitMQ

### ISSUE THREAD

**Issue by ozline** [west2-online/fzuhelper-server#30]
Currently our message queue uses rabbitmq, but we hope to change it to kafka

This is **a simple task** to get started, you only need to:

1. Introduce Kafka into our warehouse

2. Modify Kafka for the Template module and provide basic kafka function examples (for subsequent module development specifications)

3. Replace the module using RabbitMQ with Kafka (as of 2024.10.14, there should be no)

**Comment by mutezebra** [comment]
i want to try
